# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf4259625043f68f8907d1a7c4f0e2591564ec613dcf9b387484b5db15f960853f65ba6a077ad5ca972497405c826df4d868ceb2df3d237a9ba52b89b061f545

test:
  secret_key_base: e584036e1c765a26c2d8d6612b039baa2f5ebc80ecb8445d0600c543d41eaab641ecba9b9857e0745dae8e0759f7608c94e0e9abd80db215df9d5c0dde534c01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
